FROM node:18-slim AS builder

WORKDIR /build/client
COPY web/client/package*.json ./
RUN npm install
COPY web/client/ .
RUN NODE_OPTIONS=--max-old-space-size=2048 npm run build

FROM node:18-slim

WORKDIR /app/web/server
COPY web/server/package*.json ./
RUN npm install --omit=dev

COPY web/server/ .
COPY --from=builder /build/client/dist /app/web/client/dist

EXPOSE 3001

CMD ["node", "src/index.js"]
